### ISSUE TITLE
Use a config/init file

### ISSUE THREAD

**Issue by ahwmrklas** [ahwmrklas/warpWarp#10]
We need a config file loaded at startup that can fill in things like color and name and starting base etc.

This should be portable between windows and linux. I've seen a python library that gives you a portable pathname and there should be a python library for reading/writing config files. Hopefully a standard class.

**Comment by bearda** [comment]
see my work on unique_PLIDs. this should handle most of it.

The only thing I put in is the username and the PLID. obviously, it can handle more. 

Also, the server is still handing out the PLIDs (it will simply overwrite the one we created). This obviously isn't what we want, I just wanted to get some feedback on what I wrote before going through the extra effort of doing it properly..

**Comment by ahwmrklas** [comment]
The config file should be loaded and saved automatically without the
user directing it.
I guess some of the parameters could be read/written in some dialog if
we chose but normally it wouldn't be.

Start program
 If config file exists load values from it.
 If the user sets his name, write it to config file.
 If the user selects a color or starbase start selection, write it.
 If there is no "PLID" value create one and write it.
 The port # and IP address of the server should be in the config file
too. ... but right now we don't have to put anything there.

**Comment by bearda** [comment]
Right. I got all that stuff working.

I'm gonna merge with master now.
